# Generated by Django 4.0.3 on 2022-03-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENAISSANCE_COOP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
