# Generated by Django 4.0.3 on 2022-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENAISSANCE_COOP', '0002_produit_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
