# Generated by Django 4.0.3 on 2022-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENAISSANCE_COOP', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='user',
            field=models.TextField(),
        ),
    ]
